name          'puppet-laravel'
version       '0.1.0'
source        'https://github.com/lorello/laravel-puppet.git'
author        'LoreLLo'
license       'Apache 2.0'
summary       'Install and manage a webapp developed with Laravel Framework'
description   'Install and manage a webapp developed with Laravel Framework'
project_page  'https://github.com/lorello/laravel-puppet'

dependency 'puppetlabs/stdlib'
dependency 'puppetlabs/vcsrepo'
